[wip] Set up synthea for benchmarks
Error: Failed to allocate a 144 byte allocation with 70504 free bytes and 68KB until OOM, target footprint 201326592, growth limit 201326592;
giving up on allocation because <1% of heap free after GC.